version: '3.8'
services:
  web:
    build: .
    command: bin/rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle-volume:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Tickit@01'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Tickit@01'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  bundle-volume:
  my-db:
