name: "Ruby on Rails CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql2:
        image: mysql:8.0.33
        ports:
          - "3306:3306"
        env:
          MYSQL_DATABASE: attentive
          MYSQL_USER: admin
          MYSQL_PASSWORD: Tickit@01
    env:
      RAILS_ENV: test
      DATABASE_URL: "mysql2://rails:password@localhost:3306/attentive_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install RVM and Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg2 curl
          gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
          \curl -sSL https://get.rvm.io | bash -s stable --ruby=3.1.0 --gems=bundler
      - name: Set PATH for Ruby and gem executables
        run: echo "PATH=$HOME/.rvm/rubies/ruby-3.1.0/bin:$HOME/.rvm/gems/ruby-3.1.0/bin:$PATH" >> $GITHUB_ENV
      - name: Print Ruby version
        run: ruby --version
      - name: Print Bundler version
        run: bundle --version
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run tests
        run: bundle exec rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install RVM and Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg2 curl
          gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
          \curl -sSL https://get.rvm.io | bash -s stable --ruby=3.1.0 --gems=bundler
      - name: Set PATH for Ruby and gem executables
        run: echo "PATH=$HOME/.rvm/rubies/ruby-3.1.0/bin:$HOME/.rvm/gems/ruby-3.1.0/bin:$PATH" >> $GITHUB_ENV
      - name: Print Ruby version
        run: ruby --version
      - name: Print Bundler version
        run: bundle --version
      - name: Install bundler-audit
        run: bundle add bundler-audit --group development
      - name: Security audit dependencies
        run: bundle exec bundler-audit --update
      - name: Security audit application code
        run: vendor/bundle/ruby/3.1.0/bin/brakeman -q -w2
      - name: Lint Ruby files
        run: bin/rubocop --parallel
