name: "Ruby on Rails CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql2:
        image: mysql:8.0.33
        ports:
          - "3306:3306"
        env:
          MYSQL_DATABASE: attentive
          MYSQL_USER: admin
          MYSQL_PASSWORD: Tickit@01
    env:
      RAILS_ENV: test
      DATABASE_URL: "mysql2://rails:password@localhost:3306/attentive_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        run: |
          mkdir -p ~/.gem
          echo "gem: --user-install --no-document" > ~/.gemrc
          gem install bundler
          bundle config path ~/.gem
          bundle install
      - name: Print PATH
        run: echo "PATH=$PATH"
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run tests
        run: |
          export PATH="$HOME/.gem/ruby/3.1.0/bin:$PATH"
          bundle exec rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        run: |
          mkdir -p ~/.gem
          echo "gem: --user-install --no-document" > ~/.gemrc
          gem install bundler
          bundle config path ~/.gem
          bundle install
      - name: Print PATH
        run: echo "PATH=$PATH"
      - name: Security audit dependencies
        run: vendor/bundle/ruby/3.1.0/bin/bundler-audit --update
      - name: Security audit application code
        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        run: |
          export PATH="$HOME/.gem/ruby/3.1.0/bin:$PATH"
          bin/rubocop --parallel
